# Generated by Django 3.2.9 on 2021-11-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('dateSent', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
