# Generated by Django 3.2.9 on 2021-11-25 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0003_auto_20211125_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='dateSent',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
